BoragoGateR1_MapScripts::
	.byte 0


BoragoGate_R1_Teala::
	msgbox BoragoGate_R1_Teala_Text_0, MSGBOX_NPC
	return


BoragoGate_R1_RandomDude::
	msgbox BoragoGate_R1_RandomDude_Text_0, MSGBOX_NPC
	return


BoragoGate_R1_Teala_Text_0:
	.string "Hello! Beyond these gates, you'll find\n"
	.string "Borago City, the central hub of\l"
	.string "western Hanau!\p"
	.string "If you want a more relaxing spot, Turpia\n"
	.string "Town is just to the other side.\p"
	.string "Have a nice day!$"

BoragoGate_R1_RandomDude_Text_0:
	.string "Did you know? Different Pokémon will\n"
	.string "appear depending on the time of day.\p"
	.string "Kricketot and Hoothoot come out at\n"
	.string "night, but most of them sleep during\l"
	.string "the day.$"
