EverGrandeCity_House1_LowerFloor_MapScripts::
	.byte 0


Borago_H1_Mother::
	msgbox Borago_H1_Mother_Text_0, MSGBOX_NPC
	return


Borago_H1_Father::
	msgbox Borago_H1_Father_Text_0, MSGBOX_NPC
	return


Borago_H1_Mother_Text_0:
	.string "Oh, hello! My daughter is a Pokémon\n"
	.string "Trainer.\p"
	.string "If you're looking for a little help, she's\n"
	.string "the right person for the job.$"

Borago_H1_Father_Text_0:
	.string "Hey, Trainer! Have you checked out\n"
	.string "Drive Labs yet?\p"
	.string "They're in the south of the city, and\n"
	.string "they make all kinds of nifty gadgets\l"
	.string "for Trainers. Should be of help to you!$"
