EverGrandeCity_Mart_MapScripts::
	.byte 0


Borago_Map_Employee_NPC::
	msgbox Borago_Map_Employee_NPC_Text_0, MSGBOX_NPC
	return


Borago_Map_Employee_NPC_Text_0:
	.string "Welcome, welcome! We've got a nice array\n"
	.string "of products on sale! And here's\l"
	.string "another pro tip from your friendly\l"
	.string "neighborhood clerk!\p"
	.string "The more Badges you earn, the more our\n"
	.string "offers will expand to cover your\l"
	.string "ever-increasing needs. Isn't that\l"
	.string "great?$"
