gText_Birch_Welcome:: @ 82C897B
	.string "Hey there, good to see you!\p"
	.string "I take it you're participating in\nthe Pokémon competition as well?\l"
	.string "Good, good!\p"
	.string "Anyway, I'm Spruce, a Pokémon\nProfessor.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "Now, you know what a Pokémon is, right?\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "That's right! Our relationship with\n"
	.string "Pokémon goes back years upon years,\l"
	.string "and we've tried our hardest to live\l"
	.string "in harmony with them as companions.\p"
	.string "But nowadays, more and more Pokémon\n"
	.string "are threatened by human activity.\p"
	.string "That's why I specialize in Pokémon\n"
	.string "conservation.\p"
	.string "I want to know how I can help these\n"
	.string "Pokémon out.\p"
	.string "So thank you for signing up and giving\n"
	.string "me a hand!\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "All you need to do is put some scribbles\n"
	.string "here and you're good to go.\p $"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "{PLAYER}, huh… I see.\p"
	.string "Mhm. Oh, don't mind me.\p"
	.string "It's great to meet you, {PLAYER}!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "Now, why don't you go show 'em\n"
	.string "what you're made of? Off you go!\p"
	.string "$"
