EverGrandeCity_House2_LowerFloor_MapScripts::
	.byte 0


Borago_H2_Gentleman::
	msgbox Borago_H2_Gentleman_Text_0, MSGBOX_NPC
	return


Borago_H2_Socialite::
	msgbox Borago_H2_Socialite_Text_0, MSGBOX_NPC
	return


Borago_H2_Grandson::
	msgbox Borago_H2_Grandson_Text_0, MSGBOX_NPC
	return


Borago_H2_Gentleman_Text_0:
	.string "We've made the right choice in retiring\n"
	.string "here.\p"
	.string "This city gives us plenty to do, and our\n"
	.string "grandchildren love the hustle and\l"
	.string "bustle like nothing else.\p"
	.string "Quality entertainment all year round,\n"
	.string "what more could you want?$"

Borago_H2_Socialite_Text_0:
	.string "My husband and I have earned a lot of\n"
	.string "money, but we don't want to show off.\p"
	.string "We'd much rather enjoy our time\n"
	.string "together, my husband and I.\p"
	.string "After all, we're not growing any\n"
	.string "younger, are we? Hohohoho!$"

Borago_H2_Grandson_Text_0:
	.string "My parents live in Callune City. It's a\n"
	.string "little boring for me there, so my\l"
	.string "grandparents picked me up to stay\l"
	.string "here.\p"
	.string "I love Contests! I really want to\n"
	.string "become a Top Coordinator later, so I\l"
	.string "think I'm staying here a while longer.$"
