BoragoGate_MapScripts::
	.byte 0


BoragoGate_Operator::
	msgbox BoragoGate_Operator_Text_0, MSGBOX_NPC
	return


BoragoGate_YoungLady::
	msgbox BoragoGate_YoungLady_Text_0, MSGBOX_NPC
	return


BoragoGate_Man::
	msgbox BoragoGate_Man_Text_0, MSGBOX_NPC
	return


BoragoGate_Operator_Text_0:
	.string "Are you heading into the big, bustling\n"
	.string "city? Or are you going out into the\l"
	.string "wild?\p"
	.string "Either way, with this gate, you can stop\n"
	.string "to take a break in all the peace and\l"
	.string "quiet you need.$"

BoragoGate_YoungLady_Text_0:
	.string "Bag, check… Pokémon, check… P-Drive,\n"
	.string "check…\l"
	.string "Okay! I'm good to go!$"

BoragoGate_Man_Text_0:
	.string "It's nice to take a breather after a\n"
	.string "long day. Within these gates, you can\l"
	.string "just sit down and clear your mind.\l"
	.string "Whoever invented them deserves a\l"
	.string "raise!$"
